import { openaiClient, MODEL } from './openaiClient.js';
import { prompts } from './prompts.js';

const VALID_INTENTS = ['MINDFULNESS', 'JOURNAL', 'HABIT', 'CONVERSATION'];
// NOTE: INSIGHT is intentionally removed from chat routing.
// Insight reports are only generated by insightService on the /api/insights endpoint.
// Routing chat messages to insightsAnalytics caused JSON to leak into conversations.

async function classifyIntent(message) {
  const response = await openaiClient.chat.completions.create({
    model: MODEL,
    max_tokens: 10,
    temperature: 0,
    messages: [
      {
        role: 'system',
        content: `Classify this message into exactly one word: MINDFULNESS, JOURNAL, HABIT, or CONVERSATION.
Rules:
- MINDFULNESS: user wants to calm down, breathe, do an exercise, or feels stressed/anxious
- JOURNAL: user wants to write, reflect, or share feelings in writing
- HABIT: user mentions goals, routines, or habits they want to track
- CONVERSATION: anything else, or ambiguous
Reply with only the one word.`,
      },
      { role: 'user', content: message },
    ],
  });

  const raw = response.choices[0]?.message?.content?.trim().toUpperCase() ?? '';
  return VALID_INTENTS.includes(raw) ? raw : 'CONVERSATION';
}

function resolveSystemPrompt(intent, context) {
  switch (intent) {
    case 'MINDFULNESS': return prompts.mindfulnessCoach(context);
    case 'JOURNAL':     return prompts.journalingReflection(context);
    case 'HABIT':       return prompts.habitCoach(context);
    default:            return prompts.orchestrator(context);
  }
}

export async function orchestrate({ message, history = [], context }) {
  const intent = await classifyIntent(message);
  const systemPrompt = resolveSystemPrompt(intent, context);

  const messages = [
    { role: 'system', content: systemPrompt },
    ...history.map(m => ({ role: m.role, content: m.content })),
    { role: 'user', content: message },
  ];

  const response = await openaiClient.chat.completions.create({
    model: MODEL,
    max_tokens: 600,
    temperature: 0.7,
    messages,
  });

  const reply = response.choices[0]?.message?.content ?? "I'm here. Tell me more.";

  // Safety net: if reply looks like JSON, return a fallback instead of showing raw JSON
  const trimmed = reply.trim();
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    console.warn('[orchestrator] Model returned JSON in chat — using fallback.');
    return { reply: "I'm here with you. How are you feeling right now?", intent };
  }

  return { reply, intent };
}
