// Single source of truth for all mindfulness exercises.
// Used by Mindfulness page AND HabitBoard (linking to exercises).

export const EXERCISES = [
  {
    id: 'breathing_478',
    name: '4-7-8 Breathing',
    category: 'breathing',
    language: 'English',
    difficulty: 'Beginner',
    duration: '5 min',
    icon: '💨',
    description: 'Calms the nervous system. Inhale 4s, hold 7s, exhale 8s. Ideal for high stress or before sleep.',
    steps: ['Sit comfortably and close your eyes', 'Inhale through your nose for 4 seconds', 'Hold your breath for 7 seconds', 'Exhale completely through your mouth for 8 seconds', 'Repeat 3–4 times'],
    prompt: 'I would like to do the 4-7-8 breathing exercise. Please guide me through it step by step.',
  },
  {
    id: 'box_breathing',
    name: 'Box Breathing',
    category: 'breathing',
    language: 'English',
    difficulty: 'Beginner',
    duration: '4 min',
    icon: '⬜',
    description: 'Used for focus under pressure. Breathe in a 4-4-4-4 square pattern.',
    steps: ['Sit up straight', 'Exhale all air from your lungs', 'Inhale for 4 counts', 'Hold for 4 counts', 'Exhale for 4 counts', 'Hold for 4 counts', 'Repeat 4 times'],
    prompt: 'Guide me through box breathing please.',
  },
  {
    id: 'grounding_54321',
    name: '5-4-3-2-1 Grounding',
    category: 'grounding',
    language: 'English',
    difficulty: 'Beginner',
    duration: '5 min',
    icon: '🌱',
    description: 'Reconnects you to the present through your five senses. Great for anxiety or dissociation.',
    steps: ['Notice 5 things you can see', 'Touch 4 things around you', 'Listen for 3 sounds', 'Find 2 things you can smell', 'Notice 1 thing you can taste'],
    prompt: 'I feel disconnected. Please guide me through the 5-4-3-2-1 grounding exercise.',
  },
  {
    id: 'body_scan_5min',
    name: 'Body Scan',
    category: 'body scan',
    language: 'English',
    difficulty: 'Intermediate',
    duration: '5 min',
    icon: '🧘',
    description: 'A gentle scan from head to toe to release stored tension and reconnect with your body.',
    steps: ['Lie down or sit comfortably', 'Close your eyes and breathe naturally', 'Start at the top of your head', 'Slowly move attention down through each body part', 'Release any tension you notice', 'End at your feet'],
    prompt: 'Please guide me through a short 5-minute body scan meditation.',
  },
  {
    id: 'mindful_breath',
    name: 'One Mindful Breath',
    category: 'breathing',
    language: 'English',
    difficulty: 'Beginner',
    duration: '1 min',
    icon: '🌬️',
    description: 'Just one intentional breath. Perfect when you only have 60 seconds.',
    steps: ['Pause whatever you are doing', 'Take one slow, deep breath in', 'Hold for a moment', 'Let it go completely', 'Notice how you feel'],
    prompt: 'I only have one minute. Guide me through a single mindful breath.',
  },
  {
    id: 'gratitude_3',
    name: '3 Things Gratitude',
    category: 'reflection',
    language: 'English',
    difficulty: 'Beginner',
    duration: '3 min',
    icon: '✨',
    description: 'Notice three things you are grateful for right now. Shifts perspective gently.',
    steps: ['Sit quietly for a moment', 'Think of one thing you are grateful for today', 'Find a second — something small counts', 'Find a third', 'Hold all three in mind for a breath'],
    prompt: 'Help me practise a quick gratitude exercise — three things I am grateful for.',
  },
  {
    id: 'progressive_relax',
    name: 'Progressive Relaxation',
    category: 'body scan',
    language: 'English',
    difficulty: 'Intermediate',
    duration: '10 min',
    icon: '🌊',
    description: 'Tense and release each muscle group to deeply relax the body.',
    steps: ['Lie down comfortably', 'Start with your feet — tense for 5 seconds, then release', 'Move to your calves, thighs, abdomen', 'Continue through chest, hands, arms, shoulders', 'Finally tense your face muscles, then release', 'Breathe naturally and rest'],
    prompt: 'Please guide me through a progressive muscle relaxation exercise.',
  },
  {
    id: 'loving_kindness',
    name: 'Loving Kindness',
    category: 'reflection',
    language: 'English',
    difficulty: 'Intermediate',
    duration: '7 min',
    icon: '💚',
    description: 'A meditation that cultivates compassion for yourself and others.',
    steps: ['Sit comfortably and close your eyes', 'Bring yourself to mind — offer yourself kindness', 'Extend that feeling to someone you love', 'Extend it to a neutral person', 'Extend it to a difficult person', 'Finally extend it to all beings'],
    prompt: 'Guide me through a loving kindness meditation please.',
  },
];

export const EXERCISE_CATEGORIES = ['all', 'breathing', 'grounding', 'body scan', 'reflection'];

export function findExercise(id) {
  return EXERCISES.find(e => e.id === id) ?? null;
}
